# region Colors

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
SKY_BLUE = (135, 206, 250)

# endregion Colors

# region Entities

DEFAULT_DROP_HEALTH_TIMER = 60000
DEFAULT_DROP_MANA_TIMER = 60000
DEFAULT_DROP_STAMINA_TIMER = 60000

# region Player

DEFAULT_PLAYER_DAMAGE = 2
DEFAULT_PLAYER_DAMAGE_SCALE = 0.25

DEFAULT_PLAYER_HEALTH = 100
DEFAULT_PLAYER_HEALTH_BAR_BORDER = 2
DEFAULT_PLAYER_HEALTH_BAR_COLOR = RED
DEFAULT_PLAYER_HEALTH_BAR_HEIGHT = 10
DEFAULT_PLAYER_HEALTH_BAR_ORDER = 1
DEFAULT_PLAYER_HEALTH_SCALE = 0.1

DEFAULT_PLAYER_SPEED = 5
DEFAULT_PLAYER_SPEED_CROUCH_MODIFIER = -2
DEFAULT_PLAYER_SPEED_SPRINT_MODIFIER = 2

DEFAULT_PLAYER_STAMINA = 100
DEFAULT_PLAYER_STAMINA_BAR_BORDER = 2
DEFAULT_PLAYER_STAMINA_BAR_COLOR = GREEN
DEFAULT_PLAYER_STAMINA_BAR_HEIGHT = 10
DEFAULT_PLAYER_STAMINA_BAR_ORDER = 2
DEFAULT_PLAYER_STAMINA_SCALE = 0.25

DEFAULT_PLAYER_MANA = 100
DEFAULT_PLAYER_MANA_BAR_BORDER = 2
DEFAULT_PLAYER_MANA_BAR_COLOR = BLUE
DEFAULT_PLAYER_MANA_BAR_HEIGHT = 10
DEFAULT_PLAYER_MANA_BAR_ORDER = 3
DEFAULT_PLAYER_MANA_SCALE = 0.1

# endregion Player

# region Enemy

DEFAULT_ENEMY_DAMAGE = 5
DEFAULT_ENEMY_DAMAGE_SCALE = 0.1

DEFAULT_ENEMY_HEALTH = 5
DEFAULT_ENEMY_HEALTH_SCALE = 0.1

DEFAULT_ENEMY_SPEED = 10
DEFAULT_ENEMY_SPEED_CROUCH_MODIFIER = -5
DEFAULT_ENEMY_SPEED_SPRINT_MODIFIER = 5

DEFAULT_ENEMY_SPAWN_TIMER = 250

# endregion Enemy

# endregion Entities

# region StatusBar

DEFAULT_STATUS_BAR_HEIGHT = 32
DEFAULT_STATUS_BAR_FONT_SIZE = 32
DEFAULT_STATUS_BAR_FONT_COLOR = BLACK
DEFAULT_STATUS_BAR_BACKGROUND_COLOR = WHITE

# endregion StatusBar
