DEFAULT_HEALTH = 100
DEFAULT_HEALTH_REGEN = 0

DEFAULT_STAMINA = 100
DEFAULT_STAMINA_REGEN = 0.1
DEFAULT_STAMINA_DRAIN = 0.1
DEFAULT_SPRINT_STAMINA_DRAIN = DEFAULT_STAMINA_DRAIN
DEFAULT_SWIM_STAMINA_DRAIN = DEFAULT_STAMINA_DRAIN

DEFAULT_MANA = 100
DEFAULT_MANA_REGEN = 0

DEFAULT_EXPERIENCE = 0
DEFAULT_EXPERIENCE_MODIFIER = 1

DEFAULT_ARMOR = 0
DEFAULT_FIRE_RESISTANCE = 0
DEFAULT_WATER_RESISTANCE = 0
DEFAULT_ELECTRICITY_RESISTANCE = 0
DEFAULT_MAGIC_RESISTANCE = 0
DEFAULT_POISON_RESISTANCE = 0
DEFAULT_STEALTH = 0

DEFAULT_WALK_SPEED = 3
DEFAULT_WALK_SPEED_MODIFIER = 1
DEFAULT_CROUCH_SPEED_MODIFIER = 0.25
DEFAULT_SPRINT_SPEED_MODIFIER = 2.5
DEFAULT_SWIM_SPEED_MODIFIER = 0

DEFAULT_DAMAGE = 1
